version: 2.6.{build}
skip_tags: true
configuration: 
- Release
- Debug
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- ps: >-
    Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

    nuget restore -Verbosity quiet
build:
  verbosity: minimal
after_build:
- ps: >-
    if($env:CONFIGURATION -eq "Release")
    {
        Get-ChildItem ./*.vsix -Recurse | Rename-Item -NewName {$_.basename + '_' + $env:APPVEYOR_BUILD_VERSION + $_.extension }
    }
    else 
    {
        Get-ChildItem ./*.vsix -Recurse | Rename-Item -NewName {$_.basename + '_' + $env:APPVEYOR_BUILD_VERSION + '_' + $env:CONFIGURATION + $_.extension }
    } 

    Vsix-PushArtifacts | Vsix-PublishToGallery