version: 2.0.{build}
skip_tags: true
configuration: 
- Release
- Debug
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- ps: >-
    Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion

    nuget restore -Verbosity quiet
build:
  verbosity: minimal
after_build:
- ps: >-
    Get-ChildItem ./*.vsix | Rename-Item -NewName {$_.basename + '_' + $env:APPVEYOR_BUILD_VERSION + '_' + $env:CONFIGURATION $_.extension }
    Vsix-PushArtifacts | Vsix-PublishToGallery