pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - master
    - feature/*

variables:
  patch: $[counter('versioncounter', 211)]
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  group: VsixSign

name: 8.0.$(patch)

steps:
- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-NetFramework@2
  displayName: 'Update Assembly Version'
  inputs:
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'

- task: VsixToolsUpdateVersion@1
  displayName: 'Update Vsix Version (VS2019)'
  inputs:
    FileName: $(Build.SourcesDirectory)\CodeNav.VS2019\source.extension.vsixmanifest
    VersionNumber: '$(Build.BuildNumber)'

- task: VsixToolsUpdateVersion@1
  displayName: 'Update Vsix Version (VS2022)'
  inputs:
    FileName: $(Build.SourcesDirectory)\CodeNav.VS2022\source.extension.vsixmanifest
    VersionNumber: '$(Build.BuildNumber)'

- task: VSBuild@1
  displayName: 'Build Vsix'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  displayName: 'Run Tests'
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Artifacts to Staging'
  inputs: 
    contents: '**\?(*.vsix|publish-manifest.json|readme.md)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PowerShell@2
  displayName: 'Rename Build Artifacts'
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem ./*.vsix -Recurse | Rename-Item -NewName {$_.basename + "_" + $env:BUILD_BUILDNUMBER + $_.extension }'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(system.teamProject)'

- task: VsixToolsUploadVsix@2
  displayName: 'Upload Vsix to Open Gallery'